### ISSUE TITLE
Some reverse DNS lookups hanging

### ISSUE THREAD

**Issue by quickwick** [domainaware/parsedmarc#79] opened 2019-05-07 21:09 UTC
Hello,

I'm trying parsedmarc for the first time today, and have run into an issue. It appears to get stuck processing certain messages.

I'm connecting to an Exchange mailbox, via IMAP. In general, I can get it to work. I'll feed it a folder with a few hundred e-mails, it chews through them and generates the .csv and .json files.

However, it appears there are some messages it can't parse. I've let it sit for a couple of hours, no change. I turned on Debug mode, and all I get is this:

`DEBUG:__init__.py:1027:Processing message 23 of 414: UID 471`

with various values of message x of x: UID x

How can I get more useful information for you on this?

Thanks.

Edit #1 - Additional info on my setup:
Windows 10
Python 3.7.3 (fresh install)
Exchange 2013 CU 22
I downloaded that GeoLite2-Country.mmdb and put it in C:\GeoIP\ folder as per instructions

Edit #2 - I performed an elimination search, and narrowed the issue down to three report e-mails from google.com, all with large attached reports (26 KB +)

**Comment by seanthegeek** [comment] 2019-05-08 17:55
Please forward the original report emails (with the email as an attachment) to dmarc@whalensolutions.com

**Comment by seanthegeek** [comment] 2019-06-26 17:20
No response. Closing.

**Comment by quickwick** [comment] 2019-07-02 22:02
I sent the original report emails on May 13th. Though I'm realizing now they may not have connected with this issue because I sent them from my work e-mail address, and not my personal e-mail address (the one attached to this github account). Can I re-open this issue, or should I submit a new one.

Google DMARC reports are still failing to parse. I just having looked at this for a couple months, as I was waiting to get my DKIM set up before parsing any more DMARC reports.

**Comment by quickwick** [comment] 2019-07-04 01:04
I sent the original report e-mails again, this time from the e-mail account associated with this github account.

**Comment by seanthegeek** [comment] 2019-07-15 13:18
I just had a chance to look at the samples you sent, and I was able to reproduce the issue. I haven't found the cause yet, but I am working on it.

**Comment by seanthegeek** [comment] 2019-07-16 21:59
Good news. I have a fix and I'm including it in the 6.5.0 release in a few days :)

**Comment by quickwick** [comment] 2019-07-17 01:08
Great! I look forward to trying it.

**Comment by seanthegeek** [comment] 2019-07-17 15:14
@quickwick This has been fixed in parsedmarc 6.5 which was just released. The reports you have are very large, and may still take up to 8 minutes each to process in my testing, but DNS queries should no longer completely hang.

Let me know how it goes either way.

**Closed by seanthegeek** 2019-07-17 15:14 UTC
Labels: bug

**Comment by quickwick** [comment] 2019-07-23 15:32
Works, thanks. I'm not sure exactly how long it look, I had 19 google reports to parse so I just left it running overnight, but it was done in the morning.
