### ISSUE TITLE
Unable to run parsedmarc - undefined symbol: PyUnicode_New

### ISSUE THREAD

**Issue by FMCUSystemAdmins** [domainaware/parsedmarc#193] opened 2020-10-20 22:44 UTC
Hello,

We have gotten parsedmarc installed via the [pypy3 method](https://domainaware.github.io/parsedmarc/#installation-using-pypy3). When we attempt to run parsedmarc with any sort of arguments, we are met with:

`Traceback (most recent call last):
  File "./parsedmarc", line 5, in <module>
    from parsedmarc.cli import _main
  File "/opt/venvs/parsedmarc/site-packages/parsedmarc/__init__.py", line 33, in <module>
    from parsedmarc.utils import get_base_domain, get_ip_address_info
  File "/opt/venvs/parsedmarc/site-packages/parsedmarc/utils.py", line 20, in <module>
    import dateparser
  File "/opt/venvs/parsedmarc/site-packages/dateparser/__init__.py", line 4, in <module>
    from .date import DateDataParser
  File "/opt/venvs/parsedmarc/site-packages/dateparser/date.py", line 9, in <module>
    import regex as re
  File "/opt/venvs/parsedmarc/site-packages/regex/__init__.py", line 1, in <module>
    from .regex import *
  File "/opt/venvs/parsedmarc/site-packages/regex/regex.py", line 404, in <module>
    import regex._regex_core as _regex_core
  File "/opt/venvs/parsedmarc/site-packages/regex/_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ImportError: /opt/venvs/parsedmarc/site-packages/regex/_regex.pypy3-72-x86_64-linux-gnu.so: undefined symbol: PyUnicode_New`

Are you able to provide any assistance with this?

If it matters, this is on a CentOS 7 box.

Thanks,
FMCUSystemAdmins

**Comment by vppencilsharpener** [comment] 2020-10-21 12:57
Not sure if it helps, but I have the same error on a fresh install (from last night) of parsedmarc using the pypy3 method on Ubuntu 20.04 running in AWS.

**Comment by vppencilsharpener** [comment] 2020-10-21 12:59
Just realized this looks like a duplicate of #180. Unfortunately there are no replies on that one either.

**Comment by FMCUSystemAdmins** [comment] 2020-10-22 15:36
> 
> 
> Just realized this looks like a duplicate of #180. Unfortunately there are no replies on that one either.

Well that's unfortunate...

**Comment by FMCUSystemAdmins** [comment] 2020-10-22 20:21
@vppencilsharpener, we successfully installed parsedmarc following [this](https://www.linuxbabe.com/mail-server/parsedmarc-ubuntu-18-04-16-04). There is some information that is a tad outdated, so we referenced the official parsedmarc installation documentation to supplement.

If you pursue this, lmk if you hit any snags, I had a few...

**Closed** 2020-10-22 20:23 UTC

**Comment by seanthegeek** [comment] 2020-11-20 16:37
This looks like it was caused by a bug in the regex pypi package at one point. I was able to install from a fresh virtualenv just now on both Debian and Ubuntu. Please try upgrading that package within your virtualenv by running pip3 install -U regex
