### ISSUE TITLE
Enhancement: parsing TLS report

### ISSUE THREAD

**Issue by ToonDaemon** [domainaware/parsedmarc#234] opened 2021-03-24 12:30 UTC
Parsing TLSRPT reports would be nice!
https://tools.ietf.org/html/rfc8460
They seem a lot of a look a like of the dmarc reports.

**Comment by t2d** [comment] 2021-07-05 14:35
This is a duplicate of #71, isn't it?

**Comment by seanthegeek** [comment] 2022-05-02 20:54
It is indeed a duplicate of #71

**Closed by seanthegeek** 2022-05-02 20:54 UTC
